#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isBalanced' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

    
def isBalanced(s):
    list1=[]
    for x in s:
        if(x=='{'or x=='['or x=='('):
            list1.append(x)
        elif(len(list1)!=0):
            if(x=='}' and list1[-1]=='{'):
                list1.pop()
            elif(x==']' and list1[-1]=='['):
                list1.pop()
            elif(x==')' and list1[-1]=='('):
                list1.pop()
            else:
                return "NO"
        else:
            return "NO"
    if len(list1)==0:
        return "YES"
    else:
        return "NO"

                
    return s

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
