#!/bin/python3

import os
import sys

class SinglyLinkedListNode:
    def __init__(self, node_data):
        self.data = node_data
        self.next = None

class SinglyLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def insert_node(self, node_data):
        node = SinglyLinkedListNode(node_data)

        if not self.head:
            self.head = node
        else:
            self.tail.next = node


        self.tail = node

def print_singly_linked_list(node, sep, fptr):
    while node:
        fptr.write(str(node.data))

        node = node.next

        if node:
            fptr.write(sep)

def length(head1):
    l=0
    temp=head1
    while(temp is not None):
        l+=1
        temp=temp.next
    return l

def compare_lists(head1, head2):
    l1=length(head1)
    l2=length(head2)
    temp1=head1
    temp2=head2
    i=0
    if(l1==l2):
        for _ in range(l1):
            if(temp1.data==temp2.data):
                temp1=temp1.next
                temp2=temp2.next
                i+=1
                print(i)
            else:
                return 0
        if(i==l1):
            return 1
    else:
        return 0
            
    

if __name__ == '__main__':
