#!/bin/python3

import math
import os
import random
import re
import sys

def balancedSums(a):   
    n=len(a)
    s = sum(a)
    count = 0
    for i in range(n):
        if 2*count == s-a[i]:
            return("YES")
        count += a[i]
    else:
        return("NO")

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    T = int(input().strip())

    for T_itr in range(T):
        n = int(input().strip())

        arr = list(map(int, input().rstrip().split()))

        result = balancedSums(arr)

        fptr.write(result + '\n')

    fptr.close()
